In [1]:
#!pip install tensorflow

# TASK 1
 "Write a Python program that multiplies a TensorFlow tensor by a scalar value and prints the result.


In [1]:
import tensorflow as tf

# Create a TensorFlow tensor
ts = tf.constant([100, 200, 300], dtype=tf.float32)

# Define the scalar value
sc = 3.0

# Multiply the tensor by the scalar
result_tensor = tf.multiply(ts, sc)

# Print the result
print("Original Tensor:", ts.numpy())
print("Scalar Value:", sc)
print("Result Tensor (After multiplying the tensor by the scalar):", result_tensor.numpy())

Original Tensor: [100. 200. 300.]
Scalar Value: 3.0
Result Tensor (After multiplying the tensor by the scalar): [300. 600. 900.]


# TASK 2
Write a Python program that uses TensorFlow to compute the dot product of two vectors (1-D tensors).


In [2]:
import tensorflow as tf

# Define the first vector
v1 = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)

# Define the second vector
v2 = tf.constant([4.0, 5.0, 6.0], dtype=tf.float32)

# Compute the dot product of the two vectors
dot_product = tf.reduce_sum(tf.multiply(v1, v2))

# Print the result
print("Vector 1:", v1.numpy())
print("Vector 2:", v2.numpy())
print("Dot Product:", dot_product.numpy())

Vector 1: [1. 2. 3.]
Vector 2: [4. 5. 6.]
Dot Product: 32.0


# TASK 3
Write a TensorFlow program that creates two matrices, matrix1 and matrix2, with the following values:
matrix1 = [[1, 2],
                 [3, 4]]
matrix2 = [[5, 6],
                [7, 8]]
Perform the athematic operations on these matric.

In [3]:
import tensorflow as tf

# Create the first matrix
matrix1 = tf.constant([[1, 2],
                       [3, 4]], dtype=tf.float32)

# Create the second matrix
matrix2 = tf.constant([[5, 6],
                       [7, 8]], dtype=tf.float32)

# Perform addition
addition = tf.add(matrix1, matrix2)
print("Addition:\n", addition)

# Perform element-wise multiplication
elementwise_multiplication = tf.multiply(matrix1, matrix2)
print("\nElement-wise Multiplication:\n", elementwise_multiplication)

# Perform matrix multiplication
matrix_multiplication = tf.matmul(matrix1, matrix2)
print("\nMatrix Multiplication:\n", matrix_multiplication)

Addition:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)

Element-wise Multiplication:
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)

Matrix Multiplication:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [4]:
import tensorflow as tf

# Create a vector
vector = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
print("Vector:\n", vector)

# Create a scalar
scalar = tf.constant(10, dtype=tf.float32)
print("\nScalar:\n", scalar)

# Create a matrix
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]], dtype=tf.float32)
print("\nMatrix:\n", matrix)

# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]], dtype=tf.float32)
print("\nTensor:\n", tensor)

Vector:
 tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)

Scalar:
 tf.Tensor(10.0, shape=(), dtype=float32)

Matrix:
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)

Tensor:
 tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)


2. Find the shape, rank and size of the tensors you created in 1.

In [5]:
import tensorflow as tf
import numpy as np

# Tensor created in Question 5
vector = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
print("Vector:")
print("Shape:", vector.shape)
print("Rank:", vector.shape.ndims)
print("Size:", np.prod(vector.shape))
print()

# Tensor created in Question 6
scalar = tf.constant(10, dtype=tf.float32)
print("Scalar:")
print("Shape:", scalar.shape)
print("Rank:", scalar.shape.ndims)
print("Size:", np.prod(scalar.shape))
print()

# Tensor created in Question 7
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]], dtype=tf.float32)
print("Matrix:")
print("Shape:", matrix.shape)
print("Rank:", matrix.shape.ndims)
print("Size:", np.prod(matrix.shape))
print()

# Tensor created in Question 8
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]], dtype=tf.float32)
print("Tensor:")
print("Shape:", tensor.shape)
print("Rank:", tensor.shape.ndims)
print("Size:", np.prod(tensor.shape))

Vector:
Shape: (5,)
Rank: 1
Size: 5

Scalar:
Shape: ()
Rank: 0
Size: 1.0

Matrix:
Shape: (3, 3)
Rank: 2
Size: 9

Tensor:
Shape: (2, 2, 3)
Rank: 3
Size: 12


3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [6]:
import tensorflow as tf

# Create two tensors with shape [5, 300] containing random values between 0 and 1
tensor1 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)

# Print the tensors
print("Tensor 1:")
print(tensor1)
print("\nTensor 2:")
print(tensor2)

Tensor 1:
tf.Tensor(
[[0.64020944 0.9761168  0.5842539  ... 0.92757154 0.8829379  0.4196037 ]
 [0.15789437 0.21851754 0.7437575  ... 0.9792918  0.41689932 0.30318832]
 [0.59020305 0.58157    0.7218816  ... 0.04705548 0.73524964 0.5714282 ]
 [0.36958182 0.28350496 0.31469774 ... 0.08172977 0.5154159  0.56748104]
 [0.08415782 0.45049095 0.9482596  ... 0.70083964 0.8529018  0.7644193 ]], shape=(5, 300), dtype=float32)

Tensor 2:
tf.Tensor(
[[0.22159505 0.7973505  0.21192575 ... 0.8375406  0.56174874 0.63721573]
 [0.02265251 0.4683652  0.67855954 ... 0.48194325 0.4659555  0.3438282 ]
 [0.23140192 0.18164694 0.7269151  ... 0.59117377 0.04257905 0.668934  ]
 [0.7719257  0.54940224 0.44444835 ... 0.7298223  0.91765285 0.55103374]
 [0.5110959  0.68795264 0.7076999  ... 0.505203   0.79758143 0.71303916]], shape=(5, 300), dtype=float32)


4. Multiply the two tensors you created in 3 using matrix multiplication.

In [7]:
import tensorflow as tf

# Create two tensors with shape [5, 300] containing random values between 0 and 1
tensor1 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)


# Multiply the two tensors using matrix multiplication
transposed_tensor1 = tf.transpose(tensor1)
tensor_product = tf.matmul(transposed_tensor1, tensor2)

# Print the resulting tensor
print("\nTensor product:")
print(tensor_product)


Tensor product:
tf.Tensor(
[[1.2029393  1.7814785  1.456804   ... 1.5821671  0.86057127 1.2233453 ]
 [0.85713804 1.1701753  1.1915326  ... 1.638381   0.59476936 1.1202558 ]
 [0.833582   1.7407057  1.6171222  ... 0.886676   0.7535894  0.87253714]
 ...
 [0.65479225 1.0615613  0.94599956 ... 1.2205658  0.58669215 0.791223  ]
 [0.64034575 1.0778967  1.087518   ... 0.86403847 0.3289819  0.86484426]
 [0.727498   1.4363419  1.5635761  ... 1.1700091  0.4577326  1.1216078 ]], shape=(300, 300), dtype=float32)


5. Multiply the two tensors you created in 3 using dot product.

In [8]:
import tensorflow as tf

# Create two tensors with shape [5, 300] containing random values between 0 and 1
tensor1 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0.0, maxval=1.0)

# Print the tensors
print("Tensor 1:")
print(tensor1)
print("\nTensor 2:")
print(tensor2)

# Multiply the two tensors using dot product
tensor_product = tf.tensordot(tensor1, tensor2, axes=[[1], [1]])

# Print the resulting tensor
print("\nTensor product:")
print(tensor_product)

Tensor 1:
tf.Tensor(
[[0.99695706 0.6651579  0.3601333  ... 0.10567415 0.9732647  0.79180586]
 [0.13126516 0.71095884 0.01380277 ... 0.0448314  0.47244334 0.5928904 ]
 [0.62651956 0.12958884 0.9176309  ... 0.03698003 0.25952637 0.08839023]
 [0.6474335  0.33357263 0.07035589 ... 0.8128699  0.29043913 0.21469343]
 [0.6428242  0.41143334 0.27296197 ... 0.25763392 0.15794683 0.8888694 ]], shape=(5, 300), dtype=float32)

Tensor 2:
tf.Tensor(
[[0.6801393  0.17847264 0.10493982 ... 0.39302862 0.9483198  0.49303496]
 [0.46962667 0.23623645 0.09352851 ... 0.46345472 0.08347523 0.06868505]
 [0.19907296 0.8416482  0.3202771  ... 0.36533916 0.76323545 0.2797792 ]
 [0.22979057 0.8163152  0.26728547 ... 0.8815844  0.74244523 0.55373883]
 [0.41632926 0.4873891  0.9557154  ... 0.2650702  0.27314317 0.6039188 ]], shape=(5, 300), dtype=float32)

Tensor product:
tf.Tensor(
[[67.81766  70.34081  73.89763  76.64162  71.433685]
 [70.740555 75.261826 72.51328  79.147606 71.719734]
 [71.538315 74.34914  75.03

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [9]:
import tensorflow as tf

# Create a tensor with random values between 0 and 1
tensor = tf.keras.layers.Input(shape=(224, 224, 3))

# Generate a batch of random samples
samples = tf.keras.backend.random_uniform(shape=(1, 224, 224, 3))

# Print the samples
print(samples)

tf.Tensor(
[[[[0.5989486  0.68783903 0.13697422]
   [0.65451384 0.71143675 0.20342493]
   [0.7184638  0.05879951 0.21743202]
   ...
   [0.31885147 0.7074833  0.8567456 ]
   [0.5073763  0.6375313  0.01327062]
   [0.4970864  0.73669684 0.87858367]]

  [[0.24464858 0.36512196 0.9937495 ]
   [0.6639489  0.1670816  0.4427222 ]
   [0.17125821 0.23438835 0.91667473]
   ...
   [0.4251424  0.10490131 0.05941546]
   [0.95075274 0.63600385 0.8970835 ]
   [0.6039859  0.04957318 0.05729556]]

  [[0.30108285 0.7810253  0.5042217 ]
   [0.78157926 0.9796475  0.8378432 ]
   [0.80948377 0.21394491 0.10016501]
   ...
   [0.517859   0.79433227 0.16505969]
   [0.36588597 0.7055205  0.39573324]
   [0.851977   0.63127255 0.48660517]]

  ...

  [[0.8428682  0.35616004 0.70425236]
   [0.6832316  0.4986571  0.6572683 ]
   [0.18834889 0.8768778  0.05528724]
   ...
   [0.22928    0.98557556 0.99442804]
   [0.44551945 0.37791324 0.35909462]
   [0.92568433 0.10338128 0.03211343]]

  [[0.7301638  0.10218859 0.072399

7. Find the min and max values of the tensor you created in 6.

In [10]:
import tensorflow as tf

# Create a tensor with random values between 0 and 1
tensor = tf.random.uniform([224, 224, 3], minval=0, maxval=1)

# Find the minimum value of the tensor
min_value = tf.reduce_min(tensor)

# Find the maximum value of the tensor
max_value = tf.reduce_max(tensor)

# Print the minimum and maximum values
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: tf.Tensor(8.702278e-06, shape=(), dtype=float32)
Maximum value: tf.Tensor(0.9999951, shape=(), dtype=float32)


8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [11]:
import tensorflow as tf

# Create a tensor with random values of shape [1, 224, 224, 3]
tensor = tf.random.uniform([1, 224, 224, 3], minval=0, maxval=1)

# Squeeze the tensor to change the shape to [224, 224, 3]
squeezed_tensor = tf.squeeze(tensor, axis=0)

# Print the squeezed tensor
print(squeezed_tensor)

tf.Tensor(
[[[8.82415175e-01 9.84435081e-01 1.10404968e-01]
  [1.49657607e-01 5.50502300e-01 4.93664742e-01]
  [5.92301846e-01 3.37540388e-01 7.96338558e-01]
  ...
  [9.39875364e-01 9.78080392e-01 1.10979676e-01]
  [8.99058700e-01 2.22120285e-01 6.67998910e-01]
  [7.93521404e-02 1.89942837e-01 3.82443905e-01]]

 [[6.07552290e-01 7.19062924e-01 5.96724391e-01]
  [3.36555600e-01 7.24540830e-01 1.05952859e-01]
  [4.26440239e-02 7.13460445e-01 4.88586545e-01]
  ...
  [9.69097614e-01 1.32578254e-01 4.92437363e-01]
  [7.80940056e-01 1.58882499e-01 2.30111361e-01]
  [4.73810077e-01 4.11925316e-02 4.36415672e-02]]

 [[2.59062767e-01 1.24123812e-01 7.40363955e-01]
  [9.83423591e-01 2.13741183e-01 9.26341176e-01]
  [3.88996720e-01 7.84497738e-01 1.55217171e-01]
  ...
  [4.92957234e-01 9.44784760e-01 6.29107952e-01]
  [3.68623853e-01 1.89965963e-02 3.92557740e-01]
  [3.34197164e-01 2.99305439e-01 4.92501140e-01]]

 ...

 [[1.10081553e-01 9.93997097e-01 5.86717606e-01]
  [4.04523134e-01 9.89179969

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [12]:
import tensorflow as tf

# Create a tensor with shape [10] using your own choice of values
tensor = tf.constant([0.2, 0.5, 0.8, 0.3, 0.9, 0.1, 0.7, 0.4, 0.6, 0.5])

# Find the index which has the maximum value
max_index = tf.argmax(tensor)

# Print the maximum value and its index
print("Maximum value:", tf.reduce_max(tensor))
print("Index of maximum value:", max_index)

Maximum value: tf.Tensor(0.9, shape=(), dtype=float32)
Index of maximum value: tf.Tensor(4, shape=(), dtype=int64)


10. One-hot encode the tensor you created in 9.

In [13]:
import tensorflow as tf

# Create a tensor with shape [10] using your own choice of values
tensor = tf.constant([0.2, 0.5, 0.8, 0.3, 0.9, 0.1, 0.7, 0.4, 0.6, 0.5])

# Find the index which has the maximum value
max_index = tf.argmax(tensor)

# One-hot encode the tensor
one_hot_tensor = tf.one_hot(max_index, depth=tensor.shape[0])

# Print the maximum value and its index
print("Maximum value:", tf.reduce_max(tensor))
print("Index of maximum value:", max_index)

# Print the one-hot encoded tensor
print("One-hot encoded tensor:")
print(one_hot_tensor)

Maximum value: tf.Tensor(0.9, shape=(), dtype=float32)
Index of maximum value: tf.Tensor(4, shape=(), dtype=int64)
One-hot encoded tensor:
tf.Tensor([0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
